const SCENARIOS = {
  'EP:O':   { position: 'EP',  situation: 'limped',    description: 'Limped pot',      actions: 'fcr' },
  'EP:vWR': { position: 'EP',  situation: 'vs_weak',   description: 'vs weak raise',   actions: 'fc3' },
  'EP:vSR': { position: 'EP',  situation: 'vs_strong', description: 'vs strong raise', actions: 'fc3' },
  'CO:O':   { position: 'CO',  situation: 'limped',    description: 'Limped pot',      actions: 'fcr' },
  'CO:vWR': { position: 'CO',  situation: 'vs_weak',   description: 'vs weak raise',   actions: 'fc3' },
  'CO:vSR': { position: 'CO',  situation: 'vs_strong', description: 'vs strong raise', actions: 'fc3' },
  'BTN:O':  { position: 'BTN', situation: 'limped',    description: 'Limped pot',      actions: 'fcr' },
  'BTN:vWR':{ position: 'BTN', situation: 'vs_weak',   description: 'vs weak raise',   actions: 'fc3' },
  'BTN:vSR':{ position: 'BTN', situation: 'vs_strong', description: 'vs strong raise', actions: 'fc3' },
  'SB:LP':  { position: 'SB',  situation: 'limped',    description: 'Limped pot',      actions: 'fcr' },
  'B:vS':   { position: 'BB',  situation: 'vs_steal',  description: 'vs steal',        actions: 'fc3' },
  'B:vWR':  { position: 'BB',  situation: 'vs_weak',   description: 'vs weak raise',   actions: 'fc3' },
  'B:vSR':  { position: 'BB',  situation: 'vs_strong', description: 'vs strong raise', actions: 'fc3' },
  'BB:LP':  { position: 'BB',  situation: 'limped',    description: 'Limped pot',      actions: 'cr'  },
};

const SCENARIO_KEYS = ['EP:O', 'EP:vWR', 'EP:vSR', 'CO:O', 'CO:vWR', 'CO:vSR', 'BTN:O', 'BTN:vWR', 'BTN:vSR', 'SB:LP', 'B:vS', 'B:vWR', 'B:vSR', 'BB:LP'];

const SCENARIO_LABELS = {
  'EP:O':    'EP open',
  'EP:vWR':  'EP vs weak',
  'EP:vSR':  'EP vs strong',
  'CO:O':    'CO open',
  'CO:vWR':  'CO vs weak',
  'CO:vSR':  'CO vs strong',
  'BTN:O':   'BTN open',
  'BTN:vWR': 'BTN vs weak',
  'BTN:vSR': 'BTN vs strong',
  'SB:LP':   'SB limped',
  'B:vS':    'Blinds vs steal',
  'B:vWR':   'Blinds vs weak',
  'B:vSR':   'Blinds vs strong',
  'BB:LP':   'BB limped',
};

const POSITIONS = ['UTG', 'UTG+1', 'MP', 'LJ', 'HJ', 'CO', 'BTN', 'SB', 'BB'];

const RANKS = ['A', 'K', 'Q', 'J', 'T', '9', '8', '7', '6', '5', '4', '3', '2'];
const SUITS = ['♠', '♥', '♦', '♣'];

const HANDS = {
  'AA':  { 'EP:O':'r', 'EP:vWR':'3', 'EP:vSR':'3', 'CO:O':'r', 'CO:vWR':'3', 'CO:vSR':'3', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'3', 'SB:LP':'r', 'B:vS':'3', 'B:vWR':'3', 'B:vSR':'3', 'BB:LP':'r' },
  'KK':  { 'EP:O':'r', 'EP:vWR':'3', 'EP:vSR':'3', 'CO:O':'r', 'CO:vWR':'3', 'CO:vSR':'3', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'3', 'SB:LP':'r', 'B:vS':'3', 'B:vWR':'3', 'B:vSR':'3', 'BB:LP':'r' },
  'AKs': { 'EP:O':'r', 'EP:vWR':'3', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'3', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'c', 'SB:LP':'r', 'B:vS':'3', 'B:vWR':'3', 'B:vSR':'c', 'BB:LP':'r' },
  'AQs': { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'c', 'SB:LP':'r', 'B:vS':'3', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'r' },
  'AJs': { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'c', 'SB:LP':'r', 'B:vS':'3', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'r' },
  'ATs': { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'c', 'SB:LP':'r', 'B:vS':'3', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'r' },
  'A9s': { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'c', 'B:vSR':'f', 'BB:LP':'c' },
  'A8s': { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'c', 'B:vSR':'f', 'BB:LP':'c' },
  'A7s': { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'3', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'c', 'B:vSR':'f', 'BB:LP':'c' },
  'A6s': { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'c', 'B:vSR':'f', 'BB:LP':'c' },
  'A5s': { 'EP:O':'r', 'EP:vWR':'3', 'EP:vSR':'3', 'CO:O':'r', 'CO:vWR':'3', 'CO:vSR':'3', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'3', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'3', 'B:vSR':'3', 'BB:LP':'c' },
  'A4s': { 'EP:O':'r', 'EP:vWR':'3', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'3', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'3', 'B:vSR':'f', 'BB:LP':'c' },
  'A3s': { 'EP:O':'r', 'EP:vWR':'3', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'3', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'3', 'B:vSR':'f', 'BB:LP':'c' },
  'A2s': { 'EP:O':'r', 'EP:vWR':'3', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'3', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'3', 'B:vSR':'f', 'BB:LP':'c' },
  'AKo': { 'EP:O':'r', 'EP:vWR':'3', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'3', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'c', 'SB:LP':'r', 'B:vS':'3', 'B:vWR':'f', 'B:vSR':'c', 'BB:LP':'r' },
  'KQs': { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'c', 'SB:LP':'r', 'B:vS':'3', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'r' },
  'KJs': { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'c', 'SB:LP':'r', 'B:vS':'3', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'r' },
  'KTs': { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'c', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'c' },
  'K9s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'K8s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'K7s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'K6s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'K5s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'K4s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'K3s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'K2s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'AQo': { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'f', 'SB:LP':'r', 'B:vS':'3', 'B:vWR':'c', 'B:vSR':'f', 'BB:LP':'r' },
  'KQo': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'QQ':  { 'EP:O':'r', 'EP:vWR':'3', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'3', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'c', 'SB:LP':'r', 'B:vS':'3', 'B:vWR':'3', 'B:vSR':'c', 'BB:LP':'r' },
  'QJs': { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'c', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'c' },
  'QTs': { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'c', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'c' },
  'Q9s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'Q8s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'Q7s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'Q6s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'Q5s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'Q4s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'Q3s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'Q2s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'AJo': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'KJo': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'QJo': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'JJ':  { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'3', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'c', 'SB:LP':'r', 'B:vS':'3', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'r' },
  'JTs': { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'c', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'c' },
  'J9s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'J8s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'J7s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'J6s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'J5s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'J4s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'J3s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'J2s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'ATo': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'KTo': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'QTo': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'JTo': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'TT':  { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'c', 'SB:LP':'r', 'B:vS':'3', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'r' },
  'T9s': { 'EP:O':'r', 'EP:vWR':'3', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'3', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'c', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'3', 'B:vSR':'c', 'BB:LP':'c' },
  'T8s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'T7s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'T6s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'T5s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'T4s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'T3s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'T2s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'A9o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'K9o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'Q9o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'J9o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'T9o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '99':  { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'c', 'SB:LP':'r', 'B:vS':'3', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'r' },
  '98s': { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'c', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'c' },
  '97s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '96s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '95s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '94s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '93s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '92s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'A8o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'K8o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'Q8o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'J8o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'T8o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '98o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '88':  { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'c', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'c' },
  '87s': { 'EP:O':'r', 'EP:vWR':'3', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'3', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'c', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'3', 'B:vSR':'c', 'BB:LP':'c' },
  '86s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '85s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '84s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '83s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '82s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'A7o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'K7o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'Q7o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'J7o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'T7o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '97o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '87o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '77':  { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'c', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'c' },
  '76s': { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'c', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'c' },
  '75s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'3', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '74s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '73s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '72s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'A6o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'K6o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'Q6o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'J6o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'T6o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '96o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '86o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '76o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '66':  { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'c', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'c' },
  '65s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '64s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '63s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '62s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'A5o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'K5o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'Q5o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'J5o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'T5o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '95o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '85o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '75o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '65o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '55':  { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'c', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'c' },
  '54s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'3', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '53s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '52s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'A4o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'K4o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'Q4o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'J4o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'T4o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '94o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '84o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '74o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '64o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '54o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '44':  { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'c', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'c' },
  '43s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'r', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'c', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '42s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'A3o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'K3o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'Q3o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'J3o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'T3o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '93o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '83o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '73o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '63o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '53o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '43o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '33':  { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'c', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'c' },
  '32s': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'A2o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'K2o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'Q2o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'c', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'J2o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  'T2o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '92o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '82o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '72o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '62o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '52o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '42o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '32o': { 'EP:O':'f', 'EP:vWR':'f', 'EP:vSR':'f', 'CO:O':'f', 'CO:vWR':'f', 'CO:vSR':'f', 'BTN:O':'f', 'BTN:vWR':'f', 'BTN:vSR':'f', 'SB:LP':'f', 'B:vS':'f', 'B:vWR':'f', 'B:vSR':'f', 'BB:LP':'c' },
  '22':  { 'EP:O':'r', 'EP:vWR':'c', 'EP:vSR':'c', 'CO:O':'r', 'CO:vWR':'c', 'CO:vSR':'c', 'BTN:O':'r', 'BTN:vWR':'c', 'BTN:vSR':'c', 'SB:LP':'c', 'B:vS':'3', 'B:vWR':'c', 'B:vSR':'c', 'BB:LP':'c' },
};

const HAND_LIST = Object.keys(HANDS);
